import React,{useEffect,useRef,useState} from 'react';
import {useAuth} from '../../context/AuthContext';
import {useNavigate,Link} from 'react-router-dom';
import {Lock,Mail,ShieldCheck,Sparkles,AlertCircle} from 'lucide-react';
declare global { interface Window { google:any; } }
export const LoginPage:React.FC=()=>{const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');const googleRef=useRef<HTMLDivElement>(null);const {login,demoLogin,googleLogin}=useAuth();const navigate=useNavigate();
useEffect(()=>{const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(!clientId||!googleRef.current)return;const render=()=>{if(!window.google||!googleRef.current)return;window.google.accounts.id.initialize({client_id:clientId,callback:async(r:any)=>{try{setLoading(true);setError('');await googleLogin(r.credential);navigate('/')}catch(e:any){setError(e?.response?.data?.detail||'Google Sign-In failed.')}finally{setLoading(false)}}});window.google.accounts.id.renderButton(googleRef.current,{theme:'outline',size:'large',width:360,text:'continue_with'})};if(window.google)render();else{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.onload=render;document.head.appendChild(s);return()=>s.remove()}},[googleLogin,navigate]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await login(email,password);navigate('/')}catch(e:any){setError(e?.response?.data?.detail||'Sign-in failed.')}finally{setLoading(false)}};const demo=async(role:'citizen'|'admin')=>{setLoading(true);setError('');try{await demoLogin(role);navigate(role==='admin'?'/admin':'/')}catch(e:any){setError(e?.response?.data?.detail||'Demo login failed.')}finally{setLoading(false)}};
return <div className="min-h-screen bg-slate-100 flex items-center justify-center p-4"><div className="bg-white max-w-md w-full rounded-2xl shadow-xl border border-slate-200 overflow-hidden"><div className="bg-gov-blue p-6 text-white text-center border-b-4 border-gov-gold"><div className="w-12 h-12 bg-gov-gold text-slate-900 rounded-full flex items-center justify-center text-xl mx-auto mb-2 font-bold">🏛️</div><h2 className="text-xl font-bold">AccessGov AI Portal</h2><p className="text-xs text-slate-200 mt-1">Accessible Public Service Intelligence Platform</p></div><div className="bg-amber-50 p-4 border-b border-amber-200 text-xs space-y-2"><div className="flex items-center text-amber-900 font-bold"><Sparkles className="w-4 h-4 mr-1.5 text-gov-gold"/>Demo Mode</div><div className="grid grid-cols-2 gap-2"><button onClick={()=>demo('citizen')} className="py-1.5 bg-gov-blue text-white rounded font-bold">Enter as Citizen</button><button onClick={()=>demo('admin')} className="py-1.5 bg-gov-gold text-slate-900 rounded font-bold">Enter as Admin</button></div></div><form onSubmit={submit} className="p-6 space-y-4"><div><label className="block text-xs font-semibold text-slate-700 mb-1">Email / Username</label><div className="relative"><Mail className="w-4 h-4 text-slate-400 absolute left-3 top-3"/><input required value={email} onChange={e=>setEmail(e.target.value)} className="w-full text-xs border border-slate-300 rounded-md pl-9 pr-3 py-2.5"/></div></div><div><label className="block text-xs font-semibold text-slate-700 mb-1">Password</label><div className="relative"><Lock className="w-4 h-4 text-slate-400 absolute left-3 top-3"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} className="w-full text-xs border border-slate-300 rounded-md pl-9 pr-3 py-2.5"/></div></div>{error&&<div className="bg-red-50 border border-red-200 text-red-800 p-3 rounded text-xs flex gap-2"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</div>}<button type="submit" disabled={loading} className="w-full bg-gov-blue text-white font-semibold py-2.5 rounded-md text-xs flex items-center justify-center"><ShieldCheck className="w-4 h-4 mr-2 text-gov-gold"/>{loading?'Authenticating...':'Sign In'}</button><div className="text-center text-[11px] text-slate-400">OR</div><div ref={googleRef} className="flex justify-center min-h-[40px]">{!import.meta.env.VITE_GOOGLE_CLIENT_ID&&<div className="w-full text-center text-[11px] text-slate-400 border rounded py-2">Set VITE_GOOGLE_CLIENT_ID to enable Google</div>}</div><div className="text-center pt-2 text-xs text-slate-500">Don't have an account? <Link to="/register" className="text-gov-blue font-semibold">Register here</Link></div></form></div></div>};export default LoginPage;
