"""Create initial database schema

Revision ID: 01dbee19d90a
Revises: 
Create Date: 2026-10-04 17:12:13.307063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dbee19d90a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('page_or_component', sa.String(length=150), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_metrics_id'), 'accessibility_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_accessibility_metrics_metric_name'), 'accessibility_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_accessibility_metrics_page_or_component'), 'accessibility_metrics', ['page_or_component'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_hash', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_district'), 'analytics_events', ['district'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_hash'), 'analytics_events', ['user_hash'], unique=False)
    op.create_table('district_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_metrics_district_name'), 'district_metrics', ['district_name'], unique=False)
    op.create_index(op.f('ix_district_metrics_id'), 'district_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_district_metrics_metric_type'), 'district_metrics', ['metric_type'], unique=False)
    op.create_table('government_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('required_documents_summary', sa.Text(), nullable=True),
    sa.Column('processing_time_days', sa.Integer(), nullable=False),
    sa.Column('processing_days', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.String(length=50), nullable=False),
    sa.Column('validity_period', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('service_status', sa.String(length=50), nullable=False),
    sa.Column('available_online', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district_support', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_services_category'), 'government_services', ['category'], unique=False)
    op.create_index(op.f('ix_government_services_code'), 'government_services', ['code'], unique=True)
    op.create_index(op.f('ix_government_services_department'), 'government_services', ['department'], unique=False)
    op.create_index(op.f('ix_government_services_department_name'), 'government_services', ['department_name'], unique=False)
    op.create_index(op.f('ix_government_services_id'), 'government_services', ['id'], unique=False)
    op.create_index(op.f('ix_government_services_service_category'), 'government_services', ['service_category'], unique=False)
    op.create_index(op.f('ix_government_services_service_status'), 'government_services', ['service_status'], unique=False)
    op.create_index(op.f('ix_government_services_title'), 'government_services', ['title'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_rtl', sa.Boolean(), nullable=False),
    sa.Column('language_family', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'OFFICIAL', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('high_contrast_enabled', sa.Boolean(), nullable=False),
    sa.Column('font_scale', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_district'), 'users', ['district'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_number', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('rejection_reason_ai', sa.Text(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['government_services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_applications_district'), 'applications', ['district'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_service_id'), 'applications', ['service_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('conversation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.Enum('WEB_CHAT', 'VOICE', 'WHATSAPP', 'SMS', name='interactionchannel'), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('agent_used', sa.String(length=100), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('service_context', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_logs_agent_used'), 'conversation_logs', ['agent_used'], unique=False)
    op.create_index(op.f('ix_conversation_logs_id'), 'conversation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_intent'), 'conversation_logs', ['intent'], unique=False)
    op.create_index(op.f('ix_conversation_logs_service_context'), 'conversation_logs', ['service_context'], unique=False)
    op.create_index(op.f('ix_conversation_logs_session_id'), 'conversation_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_user_id'), 'conversation_logs', ['user_id'], unique=False)
    op.create_table('service_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('accepted_formats', sa.String(length=100), nullable=False),
    sa.Column('accepted_file_types', sa.String(length=100), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['government_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requirements_id'), 'service_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_service_requirements_service_id'), 'service_requirements', ['service_id'], unique=False)
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_documents_application_id'), 'uploaded_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_uploaded_documents_id'), 'uploaded_documents', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_documents_user_id'), 'uploaded_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_documents_user_id'), table_name='uploaded_documents')
    op.drop_index(op.f('ix_uploaded_documents_id'), table_name='uploaded_documents')
    op.drop_index(op.f('ix_uploaded_documents_application_id'), table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    op.drop_index(op.f('ix_service_requirements_service_id'), table_name='service_requirements')
    op.drop_index(op.f('ix_service_requirements_id'), table_name='service_requirements')
    op.drop_table('service_requirements')
    op.drop_index(op.f('ix_conversation_logs_user_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_session_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_service_context'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_intent'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_agent_used'), table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_service_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_district'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_district'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_government_services_title'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_service_status'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_service_category'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_id'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_department_name'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_department'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_code'), table_name='government_services')
    op.drop_index(op.f('ix_government_services_category'), table_name='government_services')
    op.drop_table('government_services')
    op.drop_index(op.f('ix_district_metrics_metric_type'), table_name='district_metrics')
    op.drop_index(op.f('ix_district_metrics_id'), table_name='district_metrics')
    op.drop_index(op.f('ix_district_metrics_district_name'), table_name='district_metrics')
    op.drop_table('district_metrics')
    op.drop_index(op.f('ix_analytics_events_user_hash'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_district'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_accessibility_metrics_page_or_component'), table_name='accessibility_metrics')
    op.drop_index(op.f('ix_accessibility_metrics_metric_name'), table_name='accessibility_metrics')
    op.drop_index(op.f('ix_accessibility_metrics_id'), table_name='accessibility_metrics')
    op.drop_table('accessibility_metrics')
    # ### end Alembic commands ###
